// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uvfeoztsiqhporetawic.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV2ZmVvenRzaXFocG9yZXRhd2ljIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0MjM4MTIsImV4cCI6MjA2OTk5OTgxMn0.XiKYR2spVVJMZUdoflfMn1jOY7suv2W44DfhiWwXsuM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});